import type { Metadata } from "next";
import { Alex_Brush, Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/app/Components/Footer";
import Header from "@/app/Components/Header";

const alexbrush = Alex_Brush({
  variable: "--font-alex-brush",
  weight: ["400"],
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Salão Fátima Silva",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${alexbrush.variable} ${poppins.variable}  antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
